version: '3.8'

services:
  bloglist-backend:
    image: bloglist-backend
    build:
      context: bloglist-backend
      dockerfile: dev.Dockerfile
    ports:
      - 3003:3003
    container_name: bloglist-backend
  bloglist-frontend:
    image:  bloglist-frontend
    build:
      context: bloglist-frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    